all: main.o fibo.c
	gcc main.o fibo.o -o fibo

main.o: ~/home/jovyan/work/77066004-lab/csc/code/main.c
	gcc ~home/jovyan/work/77066004-lab/csc/code/main.c -o main.o

fibo.o: ~/home/jovyan/work/77066004-lab/csc/code/fibo.c
	gcc ~/home/jovyan/work/77066004-lab/csc/code/fibo.c -o fibo.o

